export const USER_LOCAL_STORAGE_KEY = "DENGUECHAT_USER";
export const ACCESS_TOKEN_LOCAL_STORAGE_KEY = "DENGUECHAT_USER_ACCESS_TOKEN";
export const REFRESH_TOKEN_LOCAL_STORAGE_KEY = "DENGUECHAT_USER_REFRESH_TOKEN";

export const CURRENT_VISIT_LOCAL_STORAGE_KEY = "DENGUECHAT_CURRENT_VISIT";

export const CURRENT_RESOURCES_LOCAL_STORAGE_KEY =
  "DENGUECHAT_CURRENT_RESOURCES";
