import { InspectionQuestion } from "@/types";

export const INITIAL_QUESTION = 9;
export const INSPECTION_QUESTION = 0;
export const INITIAL_DB_QUESTION = 8;

export const StaticQuestions: InspectionQuestion[] = [
  {
    id: INITIAL_QUESTION,
    question: "¿Me dieron permiso para visitar la casa?",
    typeField: "list",
    options: [
      {
        id: 1,
        name: "Sí, tengo permiso para esta visita",
        required: false,
        textArea: false,
        next: 10,
      },
      {
        id: 2,
        name: "No, no me dieron permiso para esta visita",
        required: false,
        textArea: false,
        next: -1,
      },
      {
        id: 3,
        name: "La casa está cerrada",
        required: false,
        textArea: false,
        next: -1,
      },
      {
        id: 4,
        name: "La casa está deshabitada",
        required: false,
        textArea: false,
        next: -1,
      },
      {
        id: 5,
        name: "Me pidieron regresar en otra ocasión",
        required: false,
        textArea: false,
        next: -1,
      },
      {
        id: 6,
        name: "Otra explicación",
        required: false,
        textArea: false,
        next: -1,
      },
    ],
  },
  {
    id: 10,
    question: "Visitemos la casa",
    typeField: "splash",
    description:
      "Lleguemos a la casa con mucho respeto.\n\nEs importante que las personas nos sientan como alguien que les llega a apoyar para prevenir el dengue.\n\nPidamos permiso para pasar.\n\nNo lleguemos como inspectores, o para juzgar al hogar.",
    next: 11,
    image: {
      id: 8,
      url: "http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6OCwicHVyIjoiYmxvYl9pZCJ9fQ==--425559d1a1b5904f74550649547eb1af0d76a44d/En%20la%20huerta",
    },
    options: [],
  },
  {
    id: 11,
    question: "¿Quíen te acompaña hoy en esta visita?",
    typeField: "multiple",
    next: INITIAL_DB_QUESTION, // venir del back
    options: [
      {
        id: 21,
        name: "Adulto mayor",
        required: false,
        textArea: false,
      },
      {
        id: 22,
        name: "Adulto hombre",
        required: false,
        textArea: false,
      },
      {
        id: 23,
        name: "Adulto mujer",
        required: false,
        textArea: false,
      },
      {
        id: 24,
        name: "Joven hombre",
        required: false,
        textArea: false,
      },
      {
        id: 25,
        name: "Joven mujer",
        required: false,
        textArea: false,
      },
      {
        id: 26,
        name: "Niños\\as",
        required: false,
        textArea: false,
      },
    ],
  },
  {
    id: INSPECTION_QUESTION, // Init Inspection
    question: "¿Que tipo de contenedor encontraste?",
    typeField: "list",
    resourceName: "breeding_site_type_id",
    next: 21,
    options: [
      {
        id: 1,
        name: "Tanques (cemento, polietileno, metal, otro material) safas",
        required: false,
        textArea: false,
        image: true,
      },
      {
        id: 2,
        name: "Bidones o cilindros (metal, plástico)",
        required: false,
        textArea: false,
        image: true,
      },
      {
        id: 3,
        name: "Pozos",
        required: false,
        textArea: false,
        image: true,
      },
      {
        id: 4,
        name: "Estructura o partes de la casa",
        required: false,
        textArea: false,
        image: true,
      },
      {
        id: 5,
        name: "Llanta",
        required: false,
        textArea: false,
        image: true,
      },
      {
        id: 6,
        name: "Elementos naturales",
        required: false,
        textArea: false,
        image: true,
      },
      {
        id: 7,
        name: "Otros",
        required: false,
        textArea: false,
        image: true,
      },
    ],
  },
  {
    id: 21,
    question: "¿El contenedor está en uso?",
    resourceName: "in_use",
    typeField: "list",
    next: 22,
    options: [
      {
        id: 41,
        name: "Sí, está en uso",
        required: false,
        textArea: false,
        value: "true",
      },
      {
        id: 42,
        name: "No, no está en uso",
        required: false,
        textArea: false,
        value: "false",
      },
    ],
  },
  {
    id: 8,
    question: "Por favor informemos a la familia sobre",
    typeField: "multiple",
    description: null,
    next: 1,
    image: null,
    options: [
      {
        id: 1,
        name: "Explicación de larvas y pupas",
        required: true,
        textArea: false,
        image: null,
        next: null,
      },
      {
        id: 2,
        name: "Explicación sobre cómo se reproduce el zancudo",
        required: true,
        textArea: false,
        image: null,
        next: null,
      },
      {
        id: 3,
        name: "Otro tópico importante",
        required: false,
        textArea: true,
        image: null,
        next: null,
      },
    ],
  },
  {
    id: 1,
    question: "¿Dónde comienza la visita?",
    typeField: "list",
    description: null,
    next: null,
    image: null,
    options: [
      {
        id: 4,
        name: "En la huerta",
        required: false,
        textArea: false,
        image: null,
        next: 2,
      },
      {
        id: 5,
        name: "En la casa",
        required: false,
        textArea: false,
        image: null,
        next: 3,
      },
    ],
  },
  {
    id: 2,
    question: "En la huerta",
    typeField: "splash",
    description:
      "Vamos a buscar todos los recipientes que contienen agua y potencialmente son criaderos de zancudos.\n\nIniciamos la revisión de la vivienda por la derecha y finalizamos por la izquierda.",
    next: 4,
    image: {
      id: 8,
      url: "http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6OCwicHVyIjoiYmxvYl9pZCJ9fQ==--425559d1a1b5904f74550649547eb1af0d76a44d/En%20la%20huerta",
    },
    options: [],
  },
  {
    id: 3,
    question: "En la casa",
    typeField: "splash",
    description:
      "Lleguemos a la casa con mucho respeto.\n\nEs importante que las personas nos sientan como alguien que les llega a apoyar para prevenir el dengue.\n\nPidamos permiso para pasar.\n\nNo lleguemos como inspectores, o para juzgar al hogar.",
    next: 5,
    image: {
      id: 9,
      url: "http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6OSwicHVyIjoiYmxvYl9pZCJ9fQ==--61302a883c3c9515fd4ed458b62b490d14ef4828/En%20la%20casa",
    },
    options: [],
  },
  {
    id: 4,
    question: "¿Encontraste un contenedor?",
    typeField: "list",
    description: null,
    next: null,
    image: null,
    options: [
      {
        id: 6,
        name: "Sí, encontré",
        required: false,
        textArea: false,
        image: null,
        next: 0,
      },
      {
        id: 7,
        name: "No, no encontré",
        required: false,
        textArea: false,
        image: null,
        next: 3,
      },
    ],
  },
  {
    id: 5,
    question: "¿Encontraste un contenedor?",
    typeField: "list",
    description: null,
    next: null,
    image: null,
    options: [
      {
        id: 8,
        name: "Sí, encontré",
        required: false,
        textArea: false,
        image: null,
        next: 6,
      },
      {
        id: 9,
        name: "No, no encontré",
        required: false,
        textArea: false,
        image: null,
        next: -1,
      },
      {
        id: 10,
        name: "Otro",
        required: false,
        textArea: true,
        image: null,
        next: -1,
      },
    ],
  },
  {
    id: 6,
    question: "¿Qué tipo de contenedor encontraste?",
    typeField: "list",
    description: null,
    next: 7,
    image: null,
    options: [
      {
        id: 11,
        name: "Tanques (cemento, polietileno, metal, otro material)",
        required: false,
        textArea: false,
        image: {
          id: 10,
          url: "http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6MTAsInB1ciI6ImJsb2JfaWQifX0=--2a1e58a362d5b7760c9d51219b53e1123ea75ba3/Tanques%20(cemento,%20polietileno,%20metal,%20otro%20material)",
        },
        next: null,
      },
      {
        id: 12,
        name: "Bidones o cilindros (metal, plástico)",
        required: false,
        textArea: false,
        image: {
          id: 11,
          url: "http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6MTEsInB1ciI6ImJsb2JfaWQifX0=--a3e0da372479fd80059fa002a98820d33c65fbbe/Bidones%20o%20cilindros%20(metal,%20pl%C3%A1stico)",
        },
        next: null,
      },
      {
        id: 13,
        name: "Pozos",
        required: false,
        textArea: false,
        image: {
          id: 12,
          url: "http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6MTIsInB1ciI6ImJsb2JfaWQifX0=--be29a618dcc5f13ed656916351a43e45fe940541/Pozos",
        },
        next: null,
      },
      {
        id: 14,
        name: "Estructura o partes de la casa",
        required: false,
        textArea: false,
        image: {
          id: 13,
          url: "http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6MTMsInB1ciI6ImJsb2JfaWQifX0=--e22c7e1577479ac410a434abf4bac4bbcdb1ca6e/Estructura%20o%20partes%20de%20la%20casa",
        },
        next: null,
      },
      {
        id: 15,
        name: "Llanta",
        required: false,
        textArea: false,
        image: {
          id: 14,
          url: "http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6MTQsInB1ciI6ImJsb2JfaWQifX0=--fd8a5d1b69f449b3b2352d87d6fc18e749e4807e/Llanta",
        },
        next: null,
      },
      {
        id: 16,
        name: "Elementos naturales",
        required: false,
        textArea: false,
        image: {
          id: 15,
          url: "http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6MTUsInB1ciI6ImJsb2JfaWQifX0=--2c7d88e7972541a33f7771818e619645a0ad6301/Elementos%20naturales",
        },
        next: null,
      },
      {
        id: 17,
        name: "Otros",
        required: false,
        textArea: false,
        image: {
          id: 16,
          url: "http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6MTYsInB1ciI6ImJsb2JfaWQifX0=--c28286a95005995e04ea5d50d2bce3eff3ff90a8/Otros",
        },
        next: null,
      },
    ],
  },
  {
    id: 7,
    question: "¿Registrar otro contenedor?",
    typeField: "list",
    description: null,
    next: null,
    image: null,
    options: [
      {
        id: 18,
        name: "Sí, registrar",
        required: false,
        textArea: false,
        image: null,
        next: 5,
      },
      {
        id: 19,
        name: "No, no es necesario",
        required: false,
        textArea: false,
        image: null,
        next: 7,
      },
    ],
  },
  {
    id: 22,
    question: "¿El contenedor contiene agua?",
    resourceName: "has_water",
    typeField: "list",
    next: 23,
    options: [
      {
        id: 41,
        name: "Sí, contiene agua",
        required: false,
        textArea: false,
        value: "true",
      },
      {
        id: 42,
        name: "No, no contiene agua",
        required: false,
        textArea: false,
        value: "false",
      },
    ],
  },
  {
    id: 23,
    question: "¿El contenedor tiene una tapa?",
    resourceName: "has_lid",
    typeField: "list",
    next: 24,
    options: [
      {
        id: 51,
        name: "No, no tiene una tapa",
        required: false,
        textArea: false,
        value: "false",
      },
      {
        id: 52,
        name: "Sí, tiene una tapa",
        required: false,
        textArea: false,
        value: "true",
      },
    ],
  },
  {
    id: 24,
    question: "¿De donde proviene el agua?",
    resourceName: "water_source_type_id",
    typeField: "list",
    next: 25,
    options: [
      {
        id: 1,
        name: "Agua del grifo o potable",
        required: false,
        textArea: false,
      },
      {
        id: 2,
        name: "Lluvia",
        required: false,
        textArea: false,
      },
      {
        id: 3,
        name: "Otro",
        required: false,
        textArea: false,
      },
    ],
  },
  {
    id: 25,
    question:
      "En los últimos 30 días: ¿fue el contenedor tratado por el Ministerio de Salud con piriproxifeno o abate?",
    typeField: "list",
    next: 26,
    resourceName: "was_chemically_treated",
    options: [
      {
        id: 61,
        name: "Sí, fue tratado",
        required: false,
        textArea: false,
        value: "true",
      },
      {
        id: 62,
        name: "No, no fue tratado",
        required: false,
        textArea: false,
        value: "false",
      },
    ],
  },
  {
    id: 26,
    question: "En este contenedor hay",
    typeField: "list",
    resourceName: "container_test_result",
    next: 27,
    options: [
      {
        id: 1,
        name: "Larvas",
        required: false,
        textArea: false,
      },
      {
        id: 2,
        name: "Pupas",
        required: false,
        textArea: false,
      },
      {
        id: 3,
        name: "Huevos",
        required: false,
        textArea: false,
      },
      {
        id: 4,
        name: "Nada",
        required: false,
        textArea: false,
      },
    ],
  },
  {
    id: 27,
    question: "Registremos acciones tomadas sobre el contenedor",
    typeField: "splash",
    next: 28,
    options: [],
  },
  {
    id: 28,
    question: "¿Qué acción se realizó con el contenedor?",
    typeField: "list",
    resourceName: "treated_by_id",
    next: 29,
    options: [
      {
        id: 1,
        name: "Contenedor protegido",
        required: false,
        textArea: false,
      },
      {
        id: 2,
        name: "Contenedor descartado",
        required: false,
        textArea: false,
      },
      {
        id: 3,
        name: "Agua del contenedor tirada",
        required: false,
        textArea: false,
      },
      {
        id: 4,
        name: "Contenedor trasladado a un lugar seguro",
        required: false,
        textArea: false,
      },
      {
        id: 5,
        name: "Contenedor limpiado",
        required: false,
        textArea: false,
      },
    ],
  },
  {
    id: 29,
    question: "¿Puedes tomar una foto del contenedor?",
    typeField: "list",
    next: 30,
    options: [
      {
        id: 91,
        name: "Sí, puedo",
        required: false,
        textArea: false,
      },
      {
        id: 92,
        name: "No, no puedo",
        required: false,
        textArea: false,
      },
    ],
  },
  {
    id: 30,
    question: "¿Quieres hacer seguimiento de un contenedor?",
    typeField: "list",
    resourceName: "tracking_type_required",
    next: -1,
    options: [
      {
        id: 1,
        name: "Sí, hacer seguimiento",
        required: false,
        textArea: false,
      },
      {
        id: 2,
        name: "No, no es necesario",
        required: false,
        textArea: false,
      },
    ],
  },
];
