import { InspectionQuestion } from "@/types";

export const INITIAL_QUESTION = 1;
export const INITIAL_DB_QUESTION = 4;

export const StaticQuestions: InspectionQuestion[] = [
  {
    id: INITIAL_QUESTION,
    question: "¿Me dieron permiso para visitar la casa?",
    typeField: "list",
    options: [
      {
        id: 1,
        name: "Sí, tengo permiso para esta visita",
        required: false,
        textArea: false,
        next: 2,
      },
      {
        id: 2,
        name: "No, no me dieron permiso para esta visita",
        required: false,
        textArea: false,
        next: -1,
      },
      {
        id: 3,
        name: "La casa está cerrada",
        required: false,
        textArea: false,
        next: -1,
      },
      {
        id: 4,
        name: "La casa está deshabitada",
        required: false,
        textArea: false,
        next: -1,
      },
      {
        id: 5,
        name: "Me pidieron regresar en otra ocasión",
        required: false,
        textArea: false,
        next: -1,
      },
      {
        id: 6,
        name: "Otra explicación",
        required: false,
        textArea: false,
        next: -1,
      },
    ],
  },
  {
    id: 2,
    question: "Visitemos la casa",
    typeField: "splash",
    description:
      "Lleguemos a la casa con mucho respeto.\n\nEs importante que las personas nos sientan como alguien que les llega a apoyar para prevenir el dengue.\n\nPidamos permiso para pasar.\n\nNo lleguemos como inspectores, o para juzgar al hogar.",
    next: 3,
    image: {
      id: 8,
      url: "http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6OCwicHVyIjoiYmxvYl9pZCJ9fQ==--425559d1a1b5904f74550649547eb1af0d76a44d/En%20la%20huerta",
    },
    options: [],
  },
  {
    id: 3,
    question: "¿Quíen te acompaña hoy en esta visita?",
    typeField: "multiple",
    next: INITIAL_DB_QUESTION, // venir del back
    options: [
      {
        id: 1,
        name: "Adulto mayor",
        required: false,
        textArea: false,
      },
      {
        id: 2,
        name: "Adulto hombre",
        required: false,
        textArea: false,
      },
      {
        id: 3,
        name: "Adulto mujer",
        required: false,
        textArea: false,
      },
      {
        id: 4,
        name: "Joven hombre",
        required: false,
        textArea: false,
      },
      {
        id: 5,
        name: "Joven mujer",
        required: false,
        textArea: false,
      },
      {
        id: 6,
        name: "Niños\\as",
        required: false,
        textArea: false,
      },
    ],
  },
  {
    id: 4,
    question: "Por favor informemos a la familia sobre",
    typeField: "multiple",
    next: 5,
    options: [
      {
        id: 1,
        name: "Explicación de larvas y pupas",
        required: true,
        textArea: false,
      },
      {
        id: 2,
        name: "Explicación sobre cómo se reproduce el zancudo",
        required: true,
        textArea: false,
      },
      {
        id: 3,
        name: "Otro tópico importante",
        required: false,
        textArea: true,
      },
    ],
  },
  {
    id: 5,
    question: "¿Dónde comienza la visita?",
    typeField: "list",
    options: [
      {
        id: 1,
        name: "En la huerta",
        required: false,
        textArea: false,
        next: 6,
      },
      {
        id: 2,
        name: "En la casa",
        required: false,
        textArea: false,
        next: 8,
      },
    ],
  },
  {
    id: 6,
    question: "Comencemos en la huerta",
    typeField: "splash",
    description:
      "Vamos a buscar todos los recipientes que contienen agua y potencialmente son criaderos de zancudos.\n\nIniciamos la revisión de la vivienda por la derecha y finalizamos por la izquierda.",
    next: 7,
    options: [],
  },
  {
    id: 7,
    question: "¿Encontraste un contenedor?",
    typeField: "list",
    options: [
      {
        id: 1,
        name: "Sí, encontré",
        required: false,
        textArea: false,
        next: 10,
      },
      {
        id: 2,
        name: "No, no encontré",
        required: false,
        textArea: false,
        next: 8,
      },
    ],
  },
  {
    id: 8,
    question: "Revisemos dentro de la casa",
    typeField: "splash",
    description:
      "Lleguemos a la casa con mucho respeto.\n\nEs importante que las personas nos sientan como alguien que les llega a apoyar para prevenir el dengue.\n\nPidamos permiso para pasar.\n\nNo lleguemos como inspectores, o para juzgar al hogar.",
    next: 9,
    options: [],
  },
  {
    id: 9,
    question: "¿Encontraste un contenedor?",
    typeField: "list",
    options: [
      {
        id: 1,
        name: "Sí, encontré",
        required: false,
        textArea: false,
        next: 10,
      },
      {
        id: 2,
        name: "No, no encontré",
        required: false,
        textArea: false,
        next: -1,
      },
    ],
  },
  {
    id: 10,
    question: "¿Que tipo de contenedor encontraste?",
    typeField: "list",
    // resourceName: "breeding_site_type_id",
    next: 11,
    options: [
      {
        id: 1,
        name: "Tanques (cemento, polietileno, metal, otro material) safas",
        required: false,
        textArea: false,
        image: true,
      },
      {
        id: 2,
        name: "Bidones o cilindros (metal, plástico)",
        required: false,
        textArea: false,
        image: true,
      },
      {
        id: 3,
        name: "Pozos",
        required: false,
        textArea: false,
        image: true,
      },
      {
        id: 4,
        name: "Estructura o partes de la casa",
        required: false,
        textArea: false,
        image: true,
      },
      {
        id: 5,
        name: "Llanta",
        required: false,
        textArea: false,
        image: true,
      },
      {
        id: 6,
        name: "Elementos naturales",
        required: false,
        textArea: false,
        image: true,
      },
      {
        id: 7,
        name: "Otros",
        required: false,
        textArea: false,
        image: true,
      },
    ],
  },
  {
    id: 11,
    question: "¿El contenedor contiene agua?",
    // resourceName: "has_water",
    typeField: "list",
    options: [
      {
        id: 1,
        name: "Sí, contiene agua",
        required: false,
        textArea: false,
        // value: "true",
        next: 12,
      },
      {
        id: 2,
        name: "No, no contiene agua",
        required: false,
        textArea: false,
        // value: "false",
        next: 20,
      },
    ],
  },
  {
    id: 12,
    question: "¿De donde proviene el agua?",
    // resourceName: "water_source_type_id",
    typeField: "list",
    next: 13,
    options: [
      {
        id: 1,
        name: "Agua del grifo o potable",
        required: false,
        textArea: false,
      },
      {
        id: 2,
        name: "Agua activamente recogida. Ejemplo: canaleta, gotera, techo.",
        required: false,
        textArea: false,
      },
      {
        id: 3,
        name: "Agua pasivamente recogida. Ejemplo: la lluvia la llenó.",
        required: false,
        textArea: false,
      },
      {
        id: 4,
        name: "Otro",
        required: false,
        textArea: true,
      },
    ],
  },
  {
    id: 13,
    question: "¿El contenedor está protegido?",
    // resourceName: "has_lid",
    typeField: "list",
    next: 14,
    options: [
      {
        id: 1,
        name: "Sí, tiene una tapa hermética",
        required: false,
        textArea: false,
      },
      {
        id: 2,
        name: "Sí, tiene una tapa no hermética",
        required: false,
        textArea: false,
      },
      {
        id: 3,
        name: "Sí, está bajo techo",
        required: false,
        textArea: false,
      },
      {
        id: 4,
        name: "Otro tipo de protección",
        required: false,
        textArea: false,
      },
      {
        id: 5,
        name: "No tiene protección",
        required: false,
        textArea: false,
      },
    ],
  },
  {
    id: 14,
    question:
      "Pregunte si en los últimos 30 días: ¿fue el contenedor tratado por el Ministerio de Salud con piriproxifeno o abate?",
    typeField: "list",
    next: 15,
    // resourceName: "was_chemically_treated",
    options: [
      {
        id: 1,
        name: "Sí, fue tratado (revise el registro detrás de la puerta)",
        required: false,
        textArea: false,
      },
      {
        id: 2,
        name: "No, no fue tratado",
        required: false,
        textArea: false,
      },
      {
        id: 3,
        name: "No lo sé",
        required: false,
        textArea: false,
      },
    ],
  },
  {
    id: 15,
    question: "En este contenedor hay",
    typeField: "list",
    // resourceName: "content_type",
    next: 16,
    options: [
      {
        id: 1,
        name: "Larvas",
        required: false,
        textArea: false,
      },
      {
        id: 2,
        name: "Pupas",
        required: false,
        textArea: false,
      },
      {
        id: 3,
        name: "Huevos",
        required: false,
        textArea: false,
      },
      {
        id: 4,
        name: "Nada",
        required: false,
        textArea: false,
      },
    ],
  },
  {
    id: 16,
    question: "¿Hay otros contenedores como este?",
    typeField: "list",
    next: 17,
    // resourceName: "was_chemically_treated",
    options: [
      {
        id: 1,
        name: "Sí",
        required: false,
        textArea: true,
        placeholder: "¿Cuántos contenedores son?",
      },
      {
        id: 2,
        name: "No",
        required: false,
        textArea: false,
      },
    ],
  },
  {
    id: 17,
    question: "¿Puedes subir una foto del tipo de contenedor?",
    typeField: "list",
    next: 18,
    options: [
      {
        id: 1,
        name: "Sí, puedo",
        required: false,
        textArea: false,
      },
      {
        id: 2,
        name: "No, no puedo",
        required: false,
        textArea: false,
      },
    ],
  },
  {
    id: 18,
    question: "Registremos acciones tomadas sobre el contenedor",
    typeField: "splash",
    next: 19,
    options: [],
  },
  {
    id: 19,
    question: "¿Qué acción se realizó con el contenedor?",
    typeField: "list",
    // resourceName: "elimination_method_type_id",
    next: 20,
    options: [
      {
        id: 1,
        name: "El contenedor fue protegido",
        required: false,
        textArea: false,
      },
      {
        id: 2,
        name: "El contenedor fue descartado",
        required: false,
        textArea: false,
      },
      {
        id: 3,
        name: "El agua del contenedor fue tirada",
        required: false,
        textArea: false,
      },
      {
        id: 4,
        name: "El contenedor fue trasladado a un lugar seguro",
        required: false,
        textArea: false,
      },
      {
        id: 5,
        name: "El contenedor fue limpiado",
        required: false,
        textArea: false,
      },
      {
        id: 6,
        name: "Ninguna acción",
        required: false,
        textArea: false,
      },
    ],
  },
  {
    id: 20,
    question: "¿Registrar otro contenedor?",
    typeField: "list",
    options: [
      {
        id: 1,
        name: "Sí, registrar",
        required: false,
        textArea: false,
        next: 10,
      },
      {
        id: 2,
        name: "No, no es necesario",
        required: false,
        textArea: false,
        next: -1,
      },
    ],
  },
];
