import { prepareFormData } from "./prepareFormData";

describe("prepareFormData", function () {
  it("handles simple case with one container and without searching the other side of the house", function () {
    const output = prepareFormData(
      {
        "1-0": {
          value: 252,
          resourceName: "visit_permission",
          resourceId: null,
          resourceType: "attribute",
          next: 3,
          text: null,
          optionType: "boolean",
          statusColor: null,
          label: "Yes, I got permission for this visit",
          bool: true,
          weightedPoints: null,
        },
        "3-0": [
          {
            value: 258,
            resourceName: "host",
            resourceId: null,
            resourceType: "attribute",
            next: null,
            text: null,
            optionType: null,
            statusColor: null,
            disableOtherOptions: false,
            label: "Senior adult",
            weightedPoints: null,
          },
        ],
        "5-0": {
          value: 267,
          resourceName: null,
          resourceId: null,
          resourceType: "attribute",
          next: 7,
          text: null,
          optionType: null,
          statusColor: null,
          label: "In the yard/patio",
          selectedCase: "orchard",
          weightedPoints: null,
        },
        "7-0": {
          value: 269,
          resourceName: null,
          resourceId: null,
          resourceType: "attribute",
          next: 10,
          text: null,
          optionType: null,
          statusColor: null,
          label: "Yes, I did find one",
          weightedPoints: null,
        },
        "10-0": {
          value: 328,
          resourceName: "breeding_site_type_id",
          resourceId: 28,
          resourceType: "relation",
          next: null,
          text: null,
          optionType: null,
          statusColor: null,
          label: "1. Domestic use: pots, pans, glasses, buckets",
          weightedPoints: null,
        },
        "12-0": [
          {
            value: 282,
            resourceName: "water_source_type_ids",
            resourceId: 3,
            resourceType: "relation",
            next: 13,
            text: null,
            optionType: null,
            statusColor: null,
            disableOtherOptions: false,
            label: "From the faucet or from another container",
            weightedPoints: null,
          },
        ],
        "13-0": [
          {
            value: 286,
            resourceName: "container_protection_ids",
            resourceId: 1,
            resourceType: "relation",
            next: 14,
            text: null,
            optionType: null,
            statusColor: "GREEN",
            disableOtherOptions: false,
            label: "Yes, it has a sealed lid",
            weightedPoints: 9,
          },
        ],
        "14-0": {
          value: 292,
          resourceName: "was_chemically_treated",
          resourceId: null,
          resourceType: "attribute",
          next: 15,
          text: null,
          optionType: null,
          statusColor: null,
          label: "No, it was not treated",
          weightedPoints: null,
        },
        "15-0": [
          {
            value: 294,
            resourceName: "type_content_id",
            resourceId: 1,
            resourceType: "relation",
            next: 17,
            text: null,
            optionType: null,
            statusColor: "RED",
            disableOtherOptions: false,
            label: "Larvae",
            weightedPoints: 100,
          },
        ],
        "17-0": {
          value: 301,
          resourceName: "photo_id",
          resourceId: null,
          resourceType: "attribute",
          next: 18,
          text: null,
          optionType: "boolean",
          statusColor: null,
          label: "No, I can’t",
          bool: false,
          weightedPoints: null,
        },
        "19-0": [
          {
            value: 302,
            resourceName: "elimination_method_type_ids",
            resourceId: 3,
            resourceType: "relation",
            next: null,
            text: null,
            optionType: null,
            statusColor: null,
            disableOtherOptions: false,
            label: "We put a lid on the container",
            weightedPoints: null,
          },
        ],
        "20-0": {
          value: 321,
          resourceName: null,
          resourceId: null,
          resourceType: null,
          next: 4,
          text: null,
          optionType: "boolean",
          statusColor: null,
          label: "No, finish the visit",
          bool: false,
          selectedCase: "orchard",
          weightedPoints: null,
        },
        "4-1": [
          {
            value: 264,
            resourceName: "family_education_topics",
            resourceId: null,
            resourceType: "attribute",
            next: -1,
            text: null,
            optionType: null,
            statusColor: null,
            disableOtherOptions: false,
            label: "Explanation of larvae and pupae",
            weightedPoints: null,
          },
        ],
      },
      [],
    );

    expect(output).toMatchSnapshot();
  });
});
